# Generated by Django 4.1.2 on 2023-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mkubwa',
            options={'verbose_name': 'Mkubwa', 'verbose_name_plural': 'Mkubwas'},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mkubwa',
            name='is_mkubwa',
            field=models.BooleanField(default=True),
        ),
    ]
