# Generated by Django 4.1.2 on 2023-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_mkubwa_options_customer_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mkubwa',
            name='is_mkubwa',
        ),
        migrations.AddField(
            model_name='mkubwa',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
