# Generated by Django 4.1.2 on 2023-05-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_remove_mkubwa_is_mkubwa_mkubwa_is_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mkubwa',
            options={'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='mkubwa',
            name='is_customer',
        ),
    ]
